**Parkinson's diseases detection**

**Task details:**

This dataset is composed of a range of biomedical voice measurements from
31 people, 23 with Parkinson's disease (PD). Each column in the table is a
particular voice measure, and each row corresponds to one of 195 voice
recordings from these individuals ("name" column). The main aim of the data
is to discriminate healthy people from those with PD, according to the "status"
column which is set to 0 for healthy and 1 for PD.

**IMPORTING DATASET**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('/content/Parkinsson disease_mod.csv')
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [3]:
name=dataset['name']

In [4]:
dataset.drop(['name'], axis=1, inplace=True)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   MDVP:Fo(Hz)       195 non-null    float64
 1   MDVP:Fhi(Hz)      195 non-null    float64
 2   MDVP:Flo(Hz)      195 non-null    float64
 3   MDVP:Jitter(%)    195 non-null    float64
 4   MDVP:Jitter(Abs)  195 non-null    float64
 5   MDVP:RAP          195 non-null    float64
 6   MDVP:PPQ          195 non-null    float64
 7   Jitter:DDP        195 non-null    float64
 8   MDVP:Shimmer      195 non-null    float64
 9   MDVP:Shimmer(dB)  195 non-null    float64
 10  Shimmer:APQ3      195 non-null    float64
 11  Shimmer:APQ5      195 non-null    float64
 12  MDVP:APQ          195 non-null    float64
 13  Shimmer:DDA       195 non-null    float64
 14  NHR               195 non-null    float64
 15  HNR               195 non-null    float64
 16  RPDE              195 non-null    float64
 1

**TRAINING DATASET**

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)

[[1.482720e+02 1.649890e+02 1.422990e+02 ... 8.784000e-02 2.344336e+00
  1.864890e-01]
 [1.162860e+02 1.772910e+02 9.698300e+01 ... 1.339170e-01 2.058658e+00
  2.143460e-01]
 [1.636560e+02 2.008410e+02 7.677900e+01 ... 2.208900e-01 2.692176e+00
  2.159610e-01]
 ...
 [1.707560e+02 4.502470e+02 7.903200e+01 ... 3.721140e-01 2.975889e+00
  2.827800e-01]
 [2.524550e+02 2.614870e+02 1.827860e+02 ... 2.008730e-01 2.028612e+00
  8.639800e-02]
 [1.107390e+02 1.135970e+02 1.001390e+02 ... 1.923750e-01 1.889002e+00
  1.741520e-01]]


In [7]:
y_test

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1])

**DATA PREPROCESSING**

In [8]:
from sklearn.preprocessing import StandardScaler	
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**TRAINING MODEL**

In [9]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
cf=classifier.fit(X_train, y_train)


**INFORMATION ON THE MODEL**

In [10]:
cf.intercept_

array([2.41941001])

In [11]:
cf.coef_

array([[-0.36467424, -0.18963561, -0.08087498, -0.55668145, -0.40446092,
         0.35688054, -0.38936402,  0.35704717,  0.4011406 ,  0.32010808,
        -0.10063413,  0.44862599,  0.81662531, -0.1008186 , -0.07182521,
         0.45501002, -0.80293441,  0.13465027,  1.15935581,  0.65386924,
         0.57687768,  0.98886227]])

In [12]:
cf.predict_proba(X)

array([[1.00000000e+00, 8.84265750e-32],
       [1.00000000e+00, 1.05884486e-32],
       [1.00000000e+00, 3.20320845e-30],
       [1.00000000e+00, 1.44825427e-30],
       [1.00000000e+00, 8.90074528e-31],
       [1.00000000e+00, 1.05268127e-30],
       [1.00000000e+00, 1.74145447e-31],
       [1.00000000e+00, 5.11919238e-27],
       [1.00000000e+00, 9.39640496e-27],
       [1.00000000e+00, 2.63700810e-25],
       [1.00000000e+00, 1.21802714e-23],
       [1.00000000e+00, 2.69061906e-24],
       [1.00000000e+00, 7.64945975e-37],
       [1.00000000e+00, 2.20798374e-36],
       [1.00000000e+00, 1.40239327e-37],
       [1.00000000e+00, 3.71489177e-40],
       [1.00000000e+00, 6.66699206e-52],
       [1.00000000e+00, 1.08840191e-44],
       [1.00000000e+00, 2.02560810e-38],
       [1.00000000e+00, 3.95120117e-43],
       [1.00000000e+00, 8.38781075e-38],
       [1.00000000e+00, 4.53368638e-39],
       [1.00000000e+00, 7.09414314e-42],
       [1.00000000e+00, 5.37305003e-44],
       [1.000000

In [13]:
cf.score(X,y)

0.24615384615384617

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
pd.DataFrame(cm,columns=['Predicted Healthy', 'Predicted Parkinsons'], index=['True Healthy', 'True Parkinsons'])

Predicted Healthy  Predicted Parkinsons
True Healthy                     8                     3
True Parkinsons                  5                    33

In [38]:
accuracy_score(y_test, y_pred)

0.8367346938775511

**PREDICTING A RANDOM VALUE**

In [16]:
print(classifier.predict(sc.transform([[197.076, 206.896, 192.055, 0.00289, 0.00001, 0.00166, 0.00168, 0.00498,	0.01098, 0.097, 0.00563, 0.0068, 0.00802, 0.01689, 0.00339, 26.775, 0.422229, 0.741367, -7.3483, 0.177551, 1.743867, 0.085569
]])))

[0]


THE RESULT IS SAME AS THE VALUE GIVEN IN THE DATASET

In [ ]:
df = pd.DataFrame({ 'Actual': y_test, 'Predicted': y_pred})  

In [34]:
comparison_column = np.where(df["Actual"] == df["Predicted"], True, False)
df["equal"] = comparison_column
print(df)

    Actual  Predicted  equal
0        1          0  False
1        1          0  False
2        0          0   True
3        1          1   True
4        0          1  False
5        1          1   True
6        1          1   True
7        1          0  False
8        1          1   True
9        1          1   True
10       1          0  False
11       1          1   True
12       1          0  False
13       1          1   True
14       0          0   True
15       1          1   True
16       1          1   True
17       0          0   True
18       0          0   True
19       1          1   True
20       1          1   True
21       0          1  False
22       1          1   True
23       1          1   True
24       0          0   True
25       1          1   True
26       1          1   True
27       0          0   True
28       0          1  False
29       0          0   True
30       1          1   True
31       1          1   True
32       1          1   True
33       1    

In [32]:
df.value_counts()

Actual  Predicted  equal
1       1          True     33
0       0          True      8
1       0          False     5
0       1          False     3
dtype: int64